import type { Nutrients } from './types';

type UsdaNutrient = { nutrientId?: number; value?: number };
type UsdaFood = { fdcId:number; dataType?:string; description?:string; brandOwner?:string; brandName?:string; servingSize?:number; servingSizeUnit?:string; householdServingFullText?:string; foodNutrients?:UsdaNutrient[] };
export type FoodResearchResult = Nutrients & { id:string;name:string;brand:string;description:string;serving:string;servingGrams:number|null;servingsPerCookedCup:number|null;sourceLabel:string;sourceUrl:string;matchScore:number;dataType:string };
const nutrientIds={calories:1008,protein:1003,carbs:1005,fat:1004,fiber:1079,iron:1089,calcium:1087,vitaminC:1162} as const;
function nutrient(food:UsdaFood,id:number){const found=food.foodNutrients?.find((item)=>item.nutrientId===id)?.value;return found==null?null:Number(found);}
function relevance(food:UsdaFood,query:string){const text=`${food.brandName??''} ${food.brandOwner??''} ${food.description??''}`.toLowerCase();const words=query.toLowerCase().replace(/[^a-z0-9\s'-]/g,' ').split(/\s+/).filter((word)=>word.length>2&&!['cup','cooked','large','small','medium','with','and','the'].includes(word));const brand=`${food.brandName??''} ${food.brandOwner??''}`.toLowerCase();return words.reduce((score,word)=>score+(text.includes(word)?3:-3)+(brand.includes(word)?3:0),0);}
async function fetchFoods(query:string,apiKey:string,brandedOnly:boolean){const response=await fetch(`https://api.nal.usda.gov/fdc/v1/foods/search?api_key=${encodeURIComponent(apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(12000),body:JSON.stringify({query,dataType:brandedOnly?['Branded']:['Branded','Foundation','SR Legacy','Survey (FNDDS)'],pageSize:30})});if(!response.ok)throw new Error('USDA search unavailable');return((await response.json())as{foods?:UsdaFood[]}).foods??[];}
export async function researchFoods(query:string,apiKey:string,brandedOnly=false,limit=6):Promise<{results:FoodResearchResult[];searched:string}>{const cleaned=query.trim();let searched=cleaned;let foods=await fetchFoods(cleaned,apiKey,brandedOnly);const bestScore=Math.max(-99,...foods.map((food)=>relevance(food,cleaned)));const firstWord=cleaned.split(/\s+/)[0];if(firstWord.length>=4&&bestScore<5){searched=firstWord;const brandFoods=await fetchFoods(firstWord,apiKey,brandedOnly);const seen=new Set(brandFoods.map((food)=>food.fdcId));foods=[...brandFoods,...foods.filter((food)=>!seen.has(food.fdcId))];}const results=foods.sort((a,b)=>relevance(b,cleaned)-relevance(a,cleaned)).slice(0,limit).map((food):FoodResearchResult=>{const grams=/^(?:g|grm|gram)$/i.test(food.servingSizeUnit??'')?Number(food.servingSize):food.dataType==='Branded'?null:100;const scale=grams?grams/100:1;const scaled=(id:number)=>{const value=nutrient(food,id);return value==null?null:value*scale;};const brand=food.brandName||food.brandOwner||'';const description=food.description?.replace(/\s+/g,' ').trim()||'Food';return{id:String(food.fdcId),name:[brand,description].filter(Boolean).join(' · '),brand,description,dataType:food.dataType||'USDA food',serving:food.householdServingFullText||(grams?`${grams} g`:'1 serving'),servingGrams:grams,servingsPerCookedCup:/\bpasta\b/i.test(description)?1:null,calories:scaled(nutrientIds.calories)??0,protein:scaled(nutrientIds.protein)??0,carbs:scaled(nutrientIds.carbs)??0,fat:scaled(nutrientIds.fat)??0,fiber:scaled(nutrientIds.fiber)??0,iron:scaled(nutrientIds.iron),calcium:scaled(nutrientIds.calcium),vitaminC:scaled(nutrientIds.vitaminC),sourceLabel:`USDA FoodData Central · ${food.dataType||'food record'}`,sourceUrl:`https://fdc.nal.usda.gov/fdc-app.html#/food-details/${food.fdcId}/nutrients`,matchScore:relevance(food,cleaned)};});return{results,searched};}
